name: Deploy to EC2 (Blue-Green)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Java 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3️⃣ Gradle 권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4️⃣ 빌드 JAR
      - name: Build JAR
        run: ./gradlew clean build -x test

      # 5️⃣ 서버 선택 및 환경 변수 설정
      - name: Set deployment variables
        run: |
          if [ $((GITHUB_RUN_NUMBER % 2)) -eq 0 ]; then
            echo "TARGET=server1" >> $GITHUB_ENV
            echo "HOST=${{ secrets.EC2_HOST_SERVER1 }}" >> $GITHUB_ENV
          else
            echo "TARGET=server2" >> $GITHUB_ENV
            echo "HOST=${{ secrets.EC2_HOST_SERVER2 }}" >> $GITHUB_ENV
          fi
          echo "Deploying to target: $TARGET"

      # 6️⃣ SSH 키 준비
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          if [ "$TARGET" = "server1" ]; then
            echo '${{ secrets.EC2_KEY_SERVER1 }}' > ~/.ssh/ec2_key.pem
          else
            echo '${{ secrets.EC2_KEY_SERVER2 }}' > ~/.ssh/ec2_key.pem
          fi
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts 2>/dev/null || true

      # 7️⃣ JAR + Dockerfile을 EC2로 배포
      - name: Deploy app files to EC2
        run: |
          echo "Deploying to $HOST (Target: $TARGET)"
          ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no ubuntu@$HOST "mkdir -p /home/ubuntu/app"
          scp -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no build/libs/*.jar ubuntu@$HOST:/home/ubuntu/app/
          scp -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no Dockerfile ubuntu@$HOST:/home/ubuntu/app/
          ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no ubuntu@$HOST "chmod 755 /home/ubuntu/app/*.jar"

      # 8️⃣ Docker 컨테이너 재시작 (Dockerfile 사용)
      - name: Restart application with Docker
        run: |
          ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no ubuntu@$HOST "
            # 기존 컨테이너 제거
            sudo docker stop app || true
            sudo docker rm app || true
            sudo docker rmi myapp || true

            # 이미지 빌드
            echo 'Building Docker image from /home/ubuntu/app...'
            cd /home/ubuntu/app
            sudo docker build -t myapp .

            # 컨테이너 실행
            echo 'Starting new application container...'
            sudo docker run -d --name app \
              --restart unless-stopped \
              -p 8080:8080 \
              myapp

            # 헬스 체크
            echo 'Waiting for application to start...'
            sleep 10
            if sudo docker ps | grep -q 'app.*Up'; then
              echo 'Deployment successful! Application is running.'
            else
              echo 'Deployment failed! Container is not running.'
              sudo docker logs app
              exit 1
            fi
          "

      # 9️⃣ 정리
      - name: Cleanup
        if: always()
        run: rm -f ~/.ssh/ec2_key.pem